{% set version = "1.3.2" %}

package:
  name: openapi-codec
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openapi-codec/openapi-codec-{{ version }}.tar.gz
  sha256: 1bce63289edf53c601ea3683120641407ff6b708803b8954c8a876fe778d2145

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - python-coreapi >=2.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - openapi_codec

about:
  home: http://github.com/core-api/python-openapi-codec/
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: An OpenAPI codec for Core API

extra:
  recipe-maintainers:
    - lsetiawan
    - ocefpaf
